### ISSUE TITLE
Package request: libapr1.0-dev

### ISSUE THREAD

**Issue by RussiaVk** [termux/science-packages#57] opened 2021-02-06 14:18 UTC
[http://tomcat.apache.org/native-doc/](http://tomcat.apache.org/native-doc/)

Edit: Link correction

**Comment by Grimler91** [comment] 2021-02-06 15:02
Duplicate of https://github.com/termux/termux-packages/issues/6356

**Closed by Grimler91** 2021-02-06 15:02 UTC
